### ISSUE TITLE
Generating APRS messages?

### ISSUE THREAD

**Issue by mfhepp** [rossengeorgiev/aprs-python#21]
Hi, 
I am looking for a library for *generating* APRS messages in Python and I saw that at this projects supports this for at least a few basic message types.

Do you have plans to add support for encoding data into APRS payload syntax? Or do you know other Python libraries that do?

Thanks!

**Comment by rossengeorgiev** [comment]
Currently, you can only generate a position report via `aprslib.packets.PositionReport`. I'm not sure what you mean by "APRS payload syntax" and I'm not aware of other python libraries that can do what you are looking for.

**Comment by mfhepp** [comment]
Thanks! With "APRS payload syntax" I meant all the other forms of APRS messages or information field content, like telemetry.

**Comment by rossengeorgiev** [comment]
Sure, at some point those will be available

**Comment by mfhepp** [comment]
Thanks!
