### ISSUE TITLE
BASE91 Conversion Creates Invalid Value for Decimal 0 Telemetry

### ISSUE THREAD

**Issue by kb1lqc** [rossengeorgiev/aprs-python#30]
When using the base91 `from_decimal` function with an input of 0 the output is "!". However, APRS.fi which follows the [BASE91 comment telemetry](http://he.fi/doc/aprs-base91-comment-telemetry.txt) specification should actually create a "!!":

![image](https://user-images.githubusercontent.com/331540/30045805-397bbc8a-91bb-11e7-99f4-6c52890ac7ea.png)

This is rejected by aprs.fi:

Sequence = 0, Channel 1 (ADC0) = 0
![image](https://user-images.githubusercontent.com/331540/30045896-d6fe42f2-91bb-11e7-9c2a-21a0e95e27f5.png)

This turns into "|!!|" at the end of the following APRS-IS string:
![image](https://user-images.githubusercontent.com/331540/30045884-bc50a9cc-91bb-11e7-8d2e-1254b3eef924.png)

However, the specification clearly intends for sequence of 0 with channel 1 = 0 to be "|!!!!|"

![image](https://user-images.githubusercontent.com/331540/30045923-fde657d8-91bb-11e7-91ff-1e5ffbe90829.png)

**Comment by kb1lqc** [comment]
This can be mitigated with the rjust() string method

`str.rjust(2,"!")`

This pads the left with a "!" up to two characters long which is the specification.

**Comment by rossengeorgiev** [comment]
Hi @kb1lqc, the function has a second parameter to specify the width.

https://github.com/rossengeorgiev/aprs-python/blob/master/aprslib/base91.py#L54

```python
base91.from_decimal(0, width=2)

**Comment by kb1lqc** [comment]
Oh snap. I can't believe I didn't see that. I was looking right at it. Must be time to get some sleep 😴 . Thanks for quickly pointing that out!
