### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'passcode'

### ISSUE THREAD

**Issue by stroobandt** [rossengeorgiev/aprs-python#33]
The "Sending a packet" example code in the documentation is no longer valid.
`AIS = aprslib.IS("N0CALL", passcode="123456", port=14580)`
results in a `TypeError: __init__() got an unexpected keyword argument 'passcode'`

`AIS = aprslib.IS("N0CALL", "123456", port=14580)` and even 
`AIS = aprslib.IS('N0CALL', 123456, port=14580)` work though.

**Comment by rossengeorgiev** [comment]
The parameter is called `passwd`. Can you link where it says `passcode` in the docs?

**Comment by stroobandt** [comment]
<https://aprs-python.readthedocs.io/en/stable/examples.html#sending-a-packet>

**Comment by rossengeorgiev** [comment]
This was fixed in 9cee09b7
