### ISSUE TITLE
Message Id (msgNO) is being concatenated

### ISSUE THREAD

**Issue by bgmarble** [rossengeorgiev/aprs-python#36]
I just started using YAAC to test my application. Using aprs-lib I receive a message from a YAAC client with an alphanumeric 'msgNo' or message id like this, 'C0001'. Aprslib converts it to the '1'. Here is the raw packet.

[KG7AFQ-8>APJYC1,TCPIP*,qAC,T2SJC::BAKERSMS :?{C0001]

It should create a 'msgNo' like this 'C0001'.

Would you look at this?
Thanks

**Comment by rossengeorgiev** [comment]
Well yeah, that field is defined as Message Number in the protocol spec. `C0001` is not a number. The code needs to be fixed to throws a `ParseError` here.

**Comment by rossengeorgiev** [comment]
I was wrong. Reading the spec `msgNo` should be alphanumeric

**Comment by stroobandt** [comment]
This is still not in the latest PyPI release of version 0.6.46.

**Comment by rossengeorgiev** [comment]
Hi @stroobandt, try installing the package directly from the repo
