### ISSUE TITLE
unexpected keyword passcode

### ISSUE THREAD

**Issue by bhhoyer** [rossengeorgiev/aprs-python#38]
Hi,

Thanks for providing this library.

Using the example for send a packet:

import aprslib
# a valid passcode for the callsign is required in order to send
AIS = aprslib.IS("K7UDR", passcode="16273", port=14580)
AIS.connect()
# send a single status message
AIS.sendall("K7UDR>APRS,TCPIP*:>status text")

pi@WSPi:~/python/stuart $ python send.py 
Traceback (most recent call last):
  File "send.py", line 11, in <module>
    AIS = aprslib.IS("K7UDR", passcode="16273", port=14580)
TypeError: __init__() got an unexpected keyword argument 'passcode'

**Comment by bhhoyer** [comment]
figured it out deleted passcode=

**Comment by rossengeorgiev** [comment]
Hi @bhhoyer, it's `passwd`. See http://aprs-python.readthedocs.io/en/latest/examples.html#passcodes

**Comment by bhhoyer** [comment]
Thanks!
