### ISSUE TITLE
Add packet_type into the dict returned by parse.

### ISSUE THREAD

**Issue by wgaylord** [rossengeorgiev/aprs-python#41]
It would be useful to add a way to know right away what type a packet is after it can back from parse with out having to just see if it has a specific key in it. (For example currently you can tell a weather packet by looking for the key 'weather')

**Comment by wsmitchell3** [comment]
The 'format' key might be what you are looking for.

**Comment by wgaylord** [comment]
Oddly it's not returned for all types. (That I could find.) I will look again in the morning and see if I missed it.
