### ISSUE TITLE
set_filter function does not appear to work.

### ISSUE THREAD

**Issue by wgaylord** [rossengeorgiev/aprs-python#49]
After connecting to APRS-IS with the connect function I run the following to try and set a filter for only weather packets.

aprs.set_filter("t/w")

Yet I still receive all sorts of other packets. Which either means some how aprs-lib is not passing the filter allow to the server or the way to do so has changed.

My filter was made by looking at http://www.aprs-is.net/javAPRSFilter.aspx

**Comment by wgaylord** [comment]
Any suggestions?

**Comment by rossengeorgiev** [comment]
Hi @wgaylord, are you connected to a port that allows filtering?

**Comment by wgaylord** [comment]
Should have assumed I was doing something wrong. Xd 

I sort of assumed the default would support it.
