### ISSUE TITLE
Question about coordinates conversion

### ISSUE THREAD

**Issue by sp2ong** [rossengeorgiev/aprs-python#51]
How to use aprslib to convert compressed coordinates to decimal format?

lat=aprslib.xxxxx("4903.50N")
long=aprslib.xxxx("07201.75W")

**Comment by rossengeorgiev** [comment]
Hi @sp2ong, there isn't a function to do it. Here is the relevant code:

https://github.com/rossengeorgiev/aprs-python/blob/94b89a6da47a322129484efcaf1e82f6a9932891/aprslib/parsing/position.py#L99-L100

**Comment by sp2ong** [comment]
Thank you for replay. I have try use

import aprslib
form aprslib import base91

lat = 90 - (base91.to_decimal("5303.52N") / 380926.0) 
print lat

but result is strange:

-2740265826.18

**Comment by rossengeorgiev** [comment]
That is not compressed. That is just degrees, minutes and direction. There is no convenient function available to convert them to decimal format. The relevant code is here:

https://github.com/rossengeorgiev/aprs-python/blob/94b89a6da47a322129484efcaf1e82f6a9932891/aprslib/parsing/position.py#L132-L192

**Comment by sp2ong** [comment]
Ok, thank you for repaly
